from_latest_tag = false
ignore_merge_commits = false
disable_changelog = false
generate_mono_repository_global_tag = true
branch_whitelist = []
skip_ci = "[skip ci]"
skip_untracked = false
pre_bump_hooks = []
post_bump_hooks = []
pre_package_bump_hooks = []
post_package_bump_hooks = []

[git_hooks.pre-commit]
script = """
  #!/bin/sh
  set -e
  pipenv install -d
  pipenv run black --check --diff .
  pipenv run flake8 . --count --show-source --statistics
  pipenv run pytest
"""
[git_hooks.commit-msg]
script = """
  #!/bin/sh
  set -e
  cog verify --file $1
  cog check
"""

[commit_types]

[changelog]
path = "CHANGELOG.md"
template = "remote"
remote = "github.com"
repository = "robo-arena"
owner = "uni-tj"
authors = [
  { signature = "weiserhase", username = "weiserhase" },
  { signature = "JulesOxe", username = "JulesOxe" },
  { signature = "Julius Oexle", username = "JulesOxe" },
  { signature = "p-98", username = "p-98" },
  { signature = "p98", username = "p-98" },
]

[bump_profiles]

[packages]
