name: Python application

on: [push, pull_request]

permissions:
  contents: read

jobs:
  build:
    name: Python status checks
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pipenv
          pipenv install -d
          pipenv install pytest
          pipenv install flake8
          pipenv install black
          pipenv install -e .
      - name: Check formatting with black
        run: |
          # fails the tests when the code is not formatted according to black
          pipenv run black --check --diff .
      - name: Lint with flake8
        run: |
          # stop the build if flake8 doesn't pass
          pipenv run flake8 . --count --show-source --statistics
      - name: Test with pytest
        run: |
          pipenv run pytest
